// <auto-generated />
using System;
using DMCore.Data.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DMCore.Migrations
{
    [DbContext(typeof(DMDbContext))]
    partial class DMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DMCore.Data.Core.Domain.AffiliateSite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedTS");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<byte[]>("Image");

                    b.Property<string>("ImageContentType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedTS");

                    b.HasKey("Id");

                    b.ToTable("AffiliateSites");
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.AuthRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<string>("RoleName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.AuthUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AffiliateSiteId");

                    b.Property<bool>("Approved");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedTS");

                    b.Property<long?>("DealCategoryId");

                    b.Property<int>("Dislikes");

                    b.Property<DateTime>("EndTS");

                    b.Property<string>("Instructions");

                    b.Property<int>("Likes");

                    b.Property<DateTime>("StartTS");

                    b.Property<int>("Status");

                    b.Property<long>("StoreId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("URL");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedTS");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateSiteId");

                    b.HasIndex("DealCategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.Deal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AffiliateSiteId");

                    b.Property<bool>("Approved");

                    b.Property<string>("CouponCode");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedTS");

                    b.Property<bool>("DMProduct");

                    b.Property<long?>("DealCategoryId");

                    b.Property<long>("DealTagId");

                    b.Property<int>("Dislikes");

                    b.Property<DateTime>("EndTS");

                    b.Property<byte[]>("Image");

                    b.Property<string>("ImageContentType");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Instructions")
                        .IsRequired();

                    b.Property<bool>("IsCoupon");

                    b.Property<int>("Likes");

                    b.Property<string>("Price")
                        .IsRequired();

                    b.Property<DateTime>("StartTS");

                    b.Property<int>("Status");

                    b.Property<long>("StoreId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("URL")
                        .IsRequired();

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedTS");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateSiteId");

                    b.HasIndex("DealCategoryId");

                    b.HasIndex("DealTagId");

                    b.HasIndex("StoreId");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.DealCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedTS");

                    b.Property<string>("FAIcon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<bool>("PublicCategory");

                    b.Property<string>("ShortName");

                    b.Property<int>("SortSeq");

                    b.Property<string>("Status")
                        .HasMaxLength(50);

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedTS");

                    b.HasKey("Id");

                    b.ToTable("DealCategories");
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.DealTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("DealTags");
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedTS");

                    b.Property<long>("DealCategoryId");

                    b.Property<string>("Domain");

                    b.Property<byte[]>("Image");

                    b.Property<string>("ImageContentType");

                    b.Property<string>("Instructions")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("StoreTips")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedTS");

                    b.HasKey("Id");

                    b.HasIndex("DealCategoryId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.Coupon", b =>
                {
                    b.HasOne("DMCore.Data.Core.Domain.AffiliateSite", "AffiliateSite")
                        .WithMany("Coupons")
                        .HasForeignKey("AffiliateSiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMCore.Data.Core.Domain.DealCategory", "DealCategory")
                        .WithMany("Coupons")
                        .HasForeignKey("DealCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DMCore.Data.Core.Domain.Store", "Store")
                        .WithMany("Coupons")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.Deal", b =>
                {
                    b.HasOne("DMCore.Data.Core.Domain.AffiliateSite", "AffiliateSite")
                        .WithMany("Deals")
                        .HasForeignKey("AffiliateSiteId");

                    b.HasOne("DMCore.Data.Core.Domain.DealCategory", "DealCategory")
                        .WithMany("Deals")
                        .HasForeignKey("DealCategoryId");

                    b.HasOne("DMCore.Data.Core.Domain.DealTag", "DealTag")
                        .WithMany("Deals")
                        .HasForeignKey("DealTagId");

                    b.HasOne("DMCore.Data.Core.Domain.Store", "Store")
                        .WithMany("Deals")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DMCore.Data.Core.Domain.Store", b =>
                {
                    b.HasOne("DMCore.Data.Core.Domain.DealCategory", "DealCategory")
                        .WithMany("Stores")
                        .HasForeignKey("DealCategoryId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DMCore.Data.Core.Domain.AuthRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DMCore.Data.Core.Domain.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DMCore.Data.Core.Domain.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DMCore.Data.Core.Domain.AuthRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DMCore.Data.Core.Domain.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DMCore.Data.Core.Domain.AuthUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
